---

- name: Transfer LLIIA Logo
  copy:
    src: LLIIA_Logo.png
    dest: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/resources/assets/LLIIA_Logo.png"

- name: Install LLIIA Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/LocalSettings.php"
    regexp: ^\$wgLogo = .*
    line: $wgLogo = "$wgResourceBasePath/resources/assets/LLIIA_Logo.png";
