---

- hosts: mysql
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mysql
  
- hosts: mediawiki
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mediawiki
    - embed_video
    - torque
    - permissions
    - emulategroup
    - 100Change2020Demo
    - finishmediawiki
