---

- hosts: mediawiki
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mediawiki
    - activitylog
    - collection
    - embed_video
    - permissions
    - simplefavorites
    # PickSome has to come after collection so the left menu bar is correct
    - picksome
    - simplesaml
    - rss
    - teamcomments
    - torquedataconnect
    # This should come after permissions because of overrides of defaults
    - 100Change2020
    # This should always go last, to run db updates and restart
    - finishmediawiki

- hosts: simplesaml
  become: true
  become_user: "{{ deployment_user }}"
  roles:
  - simplesaml

