---

- name: Check out TeamComments
  git:
    repo: https://github.com/OpenTechStrategies/TeamComments
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/extensions/TeamComments/"
    version: 97a607d

- name: Enable TeamComments
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE TEAMCOMMENTS CONFIG"
    block: |
      wfLoadExtension('TeamComments');
      $wgTeamCommentsCheatSheetLocation = "Wiki_Markup_Cheat_Sheet";
      $wgTeamCommentsUserPseudonymizer = function($username) {
        return "Pseudonymous User #" . TorqueDataConnectUserLookup::lookupByUsername($username)->{"id"};
      };

