---

- name: Check out ActivityLog
  git:
    repo: https://github.com/OpenTechStrategies/ActivityLog
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/extensions/ActivityLog/"
    version: 27e9191

- name: Install ActivityLog Configuration
  copy:
    src: ActivityLogConfiguration
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/"

- name: Transfer Config
  copy:
    src: activity-log.php
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/"

- name: Enable ActivityLog
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE ACTIVITYLOG CONFIG"
    block: |
      include "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/activity-log.php";
