---

- name: Transfer EO Logo
  copy:
    src: "{{ lookup('env','OTS_DIR') }}/clients/lever-for-change/torque-sites/EO2020/data/EOLogo.png"
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/resources/assets/EOLogo.png"

- name: Transfer LFC Logo
  copy:
    src: LeverForChange_Logo.svg
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/resources/assets/LeverForChange_Logo.svg"

- name: Install LFC Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    regexp: ^\$wgLogos = .*
    line: $wgLogos = [ 'svg' => "$wgResourceBasePath/resources/assets/LeverForChange_Logo.svg" ];

- name: Override base pluggable auth config
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE PLUGABLE AUTH OVERRIDE CONFIG"
    block: |
      $wgPluggableAuth_EnableLocalLogin = true;
