---

- name: Transfer RacialEquity2030 Logo
  copy:
    src: RacialEquity2030_Logo.png
    dest: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/resources/assets/RacialEquity2030_Logo.png"

- name: Install RacialEquity2030 Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/LocalSettings.php"
    regexp: ^\$wgLogo = .*
    line: $wgLogo = "$wgResourceBasePath/resources/assets/RacialEquity2030_Logo.png";
