---

- name: Transfer RacialEquity2030 Logo
  copy:
    src: RacialEquity2030_Logo.png
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/resources/assets/RacialEquity2030_Logo.png"

- name: Install RacialEquity2030 Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    regexp: ^\$wgLogos = .*
    line: $wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/RacialEquity2030_Logo.png" ];
