---

- name: Transfer LFC Logo
  copy:
    src: 100Change-logo150.png
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/resources/assets/100Change-logo150.png"

- name: Install LFC Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    regexp: ^\$wgLogos = .*
    line: $wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/100Change-logo150.png" ];

- name: Override base pluggable auth config
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE PLUGABLE AUTH OVERRIDE CONFIG"
    block: |
      $wgPluggableAuth_EnableLocalLogin = true;
