---

- name: Checkout PickSome
  git:
    repo: https://github.com/OpenTechStrategies/PickSome
    dest: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/extensions/PickSome/"
    version: 59df890

- name: Enable PickSome
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/LocalSettings.php"
    marker: "## {mark} ANSIBLE PICKSOME CONFIG"
    block: |
      # While this next line should be taken care of in extenions, and indeed
      # it is, because this extension is loaded via wfLoadExtension, and because
      # Collection is loaded the old way, the sidebar before output is called
      # preferring Collection, placing it higher on the siderbar than PickSome.
      #
      # This was requested to be changed, and the most straightforward way is
      # to add it to the hook directly in LocalSettings
      $wgHooks['SidebarBeforeOutput'][] = 'PickSomeHooks::onSidebarBeforeOutput';
      wfLoadExtension('PickSome');
      $wgPickSomeNumberOfPicks = 15;
      # This may not be performant and require caching if number of users/page hits
      # becomes large.
      $wgPickSomePage = function($title) {
        $eligibleWildCardsTitle = Title::newFromText("TorqueConfig:ValidProposals");
        if($eligibleWildCardsTitle->exists()) {
          $page = new WikiPage($eligibleWildCardsTitle);
          $valid_pages = [];
          preg_match_all("/\\[\\[([^\\]]*)\\]\\]/", $page->getContent()->getText(), $valid_pages);
          foreach($valid_pages[1] as $valid_page) {
            if($title->equals(Title::newFromText($valid_page))) {
              return true;
            }
          }
          return false;
        } else {
          return false;
        }
      };

      $wgPickSomeSortFunction = function($t1, $t2) {
        $text1 = $t1->getText();
        $text2 = $t2->getText();

        $text1 = preg_replace("/^\\W/", "", $text1);
        $text2 = preg_replace("/^\\W/", "", $text2);
        return $text1 > $text2;
      };

      $picksomeOverrideMessage = [
        "picksome-all" => "Everyone's Finalist Candidates",
        "picksome-title" => "Finalist Candidates",
        "picksome-choices" => "Finalist Candidate Choices",
        "picksome-my-picks" => "My Finalist Candidates",
        "picksome-unpick" => "Deselect",
        "picksome-pick" => "Select this page",
        "picksome-no-picks" => "No Finalist Candidates",
        "picksome-current" => "Current Page",
        "picksome-view-all" => "View Everyone's Finalist Candidates",
        "picksome-global-list" => "Global Finalist Candidate List",
        "picksome-remove-below" => "To select the current page, remove one below",
        "picksome-stop" => "Stop Selecting",
        "picksome-close-window" => "Close Window",
        "picksome-start" => "Start Selecting",
      ];
      $wgHooks['MessagesPreLoad'][] = function($title, &$message, $code) {
        global $picksomeOverrideMessage;
        if(array_key_exists(strtolower($title), $picksomeOverrideMessage)) {
          $message = $picksomeOverrideMessage[strtolower($title)];
        }
      };

