---

- name: Check out PickSome
  git:
    repo: https://github.com/OpenTechStrategies/PickSome
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/extensions/PickSome/"
    version: 59df890

- name: Transfer Config
  copy:
    src: picksome.php
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/"

- name: Enable PickSome
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE PICKSOME CONFIG"
    block: |
      include "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/picksome.php";
