---

- name: Transfer ECW2020 Logo
  copy:
    src: ECW2020_Logo.png
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/resources/assets/ECW2020_Logo.png"

- name: Install ECW2020 Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    regexp: ^\$wgLogos = .*
    line: $wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/ECW2020_Logo.png" ];

- name: Clear pluggable auth override config
  blockinfile:
    marker: "## {mark} ANSIBLE PLUGABLE AUTH OVERRIDE CONFIG"
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"

- name: Clear picksome override config
  blockinfile:
    marker: "## {mark} ANSIBLE PICKSOME OVERRIDE CONFIG"
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"

- name: Override some PickSome Variables
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE PICKSOME OVERRIDE CONFIG"
    block: |
      $wgPickSomeNumberOfPicks = 4;

- name: Override base permissions auth config
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE PERMISSIONS OVERRIDE CONFIG"
    block: |
      $wgGroupPermissions['LFCEvaluators']['teamcomment'] = false;
      $wgGroupPermissions['DecisionMakers']['teamcomment'] = false;
