---

- name: Check out SimpleBook
  git:
    repo: https://github.com/OpenTechStrategies/SimpleBook
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/extensions/SimpleBook"
    version: "{{ simplebook_git_version }}"

- name: Transfer Config
  template:
    src: simplebook.php.j2
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/simplebook.php"

- name: Enable SimpleBook
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE SIMPLEBOOK CONFIG"
    block: |
      include "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/simplebook.php";
