---
  
- hosts: mediawiki
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mediawiki
    - activitylog
    - collection
    - embed_video
    - permissions
    - simplefavorites
    - simplesaml
    - teamcomments
    - torquedataconnect
    - EO2020
    # This should always go last, to run db updates and restart
    - finishmediawiki

- hosts: simplesaml
  become: true
  become_user: "{{ deployment_user }}"
  roles:
  - simplesaml
