---

- name: Clear pluggable auth override config
  blockinfile:
    marker: "## {mark} ANSIBLE PLUGABLE AUTH OVERRIDE CONFIG"
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"

# Because the overrides MUST come after the originals (loaded from include statements)
# in LocalSettings, we delete the overrides from the file, and then re-insert them to
# ensure that they comes at the end of the LocalSettings file
- name: Clear picksome override config
  blockinfile:
    marker: "## {mark} ANSIBLE PICKSOME OVERRIDE CONFIG"
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"

- name: Override some PickSome Variables
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE PICKSOME OVERRIDE CONFIG"
    block: |
      $wgPickSomeNumberOfPicks = 5;
      $wgLFCPickSomeEligiblePage = "TorqueConfig:FinalistCandidates";

- name: Transfer LFC Logo
  copy:
    src: LeverForChange_Logo.png
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/resources/assets/LeverForChange_Logo.png"

- name: Install LFC Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    regexp: ^\$wgLogos = .*
    line: $wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/LeverForChange_Logo.png" ];

- name: Install additional tab configurations
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE ADDITIONAL TAB CONFIG"
    block: |
      # Overwrite the whole variable since 100&Change 2020 is unique in handling of tabs
      $wgLFCExtraTabs = [
        ["Overview", "Solution Overview", "main"],
        ["Prospectus for ", "Prospectus", "prospectus"],
        ["Analysis of ",  "Analysis", "analysis"],
        ["Diligence for ", "Diligence", "diligence"],
        ["Original Proposal for ", "Original Proposal", "originalproposal"]
      ];
