---
  
- hosts: mediawiki
  become: true
  become_user: "{{ deployment_user }}"
  roles:
  - mediawiki

- hosts: simplesaml
  become: true
  become_user: "{{ deployment_user }}"
  roles:
  - simplesaml
