---
- hosts: mysql
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mysql

- hosts: mediawiki
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mediawiki
    - activitylog
    - simplebook
    - embed_video
    - permissions
    - simplefavorites
    - torque
    - exporttables
    - simplesaml
    - simplemaps
    - emulategroup
    - GlobalView
    # This should always go last, to run db updates and restart
    - finishmediawiki
