---

- name: Transfer LFC Logo
  copy:
    src: LeverForChange_Logo.svg
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/resources/assets/LeverForChange_Logo.svg"

- name: Install LFC Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    regexp: ^\$wgLogos = .*
    line: $wgLogos = [ 'svg' => "$wgResourceBasePath/resources/assets/LeverForChange_Logo.svg" ];
