---

- name: Transfer Democracy22 Logo
  copy:
    src: Democracy22_Logo.svg
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/resources/assets/Democracy22_Logo.svg"

- name: Install Democracy22 Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    regexp: ^\$wgLogos = .*
    line: $wgLogos = [ 'svg' => "$wgResourceBasePath/resources/assets/Democracy22_Logo.svg" ];
