---

- hosts: mysql
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mysql

- hosts: mediawiki
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mediawiki
    - permissions
    - simplefavorites
    - simplesaml
    - exporttables
    # This should come after permissions because of overrides of defaults
    - helpwiki
    # This should always go last, to run db updates and restart
    - finishmediawiki
