---

- name: install prerequisites
  become_user: root
  # See https://www.mediawiki.org/wiki/Manual:Installation_requirements
  apt:
    name: "{{ item }}"
    #update_cache: yes # commented out for dev purposes
    state: present
  loop:
    - pipenv
    - postgresql
    - python-psycopg2
    - supervisor

- name: Create database user
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    state: present

- name: create postgresql db
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ supervisor_torquedata_name }}"
    state: present
    owner: "{{ db_username }}"

- name: Setup installation directory
  file:
    path: "{{ torquedata_install_directory }}"
    state: directory

- name: Check out Torque
  git:
    repo: https://github.com/OpenTechStrategies/torque
    dest: "{{ torquedata_install_directory }}/torque/"
    version: "{{ torquedata_git_version }}"

- name: Link TorqueData
  file:
    src: "{{ torquedata_install_directory }}/torque/torquedata/"
    dest: "{{ torquedata_install_directory }}/server"
    state: link

- name: Run pipenv install
  command: "pipenv install"
  args:
    chdir: "{{ torquedata_install_directory }}/server"

- name: Install torquedata configuration
  template:
    src: config.py.j2
    dest: "{{ torquedata_install_directory }}/server/config.py"

- name: Run Migrations
  command: "pipenv run python manage.py migrate"
  args:
    chdir: "{{ torquedata_install_directory }}/server"

- name: Install torquedata supervisor
  become_user: root
  template:
    src: supervisor-torquedata.conf.j2
    dest: /etc/supervisor/conf.d/{{ supervisor_torquedata_name}}.conf

- name: Restart supervisor for torquedata
  become_user: root
  supervisorctl:
    name: "{{ supervisor_torquedata_name }}"
    state: restarted
