---

- name: Create torqueadmin user
  command: "php {{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/maintenance/createAndPromote.php --force --dbuser=\"{{ db_username }}\" --dbpass=\"{{ db_password }}\" --custom-groups=\"TorqueAdmin\" \"{{ mediawiki_torqueadmin_username }}\" \"{{ mediawiki_torqueadmin_password }}\""
  when: mediawiki_torqueadmin_username is defined

# This should come near the end to make sure that all the database updates
# for the extensions get run after the rest of the system is set up.
- name: Run mediawiki updates
  command: "php {{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/maintenance/update.php"

- name: Restart Apache
  become_user: root
  service:
    name: apache2
    state: restarted
