---

- hosts: mysql
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mysql

- hosts: mediawiki
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mediawiki
    - activitylog
    - simplebook
    - embed_video
    - permissions
    # PickSome has to come after SimpleBook so the left menu bar is correct
    #- picksome # disabled due to client request on Jan 14, 2021
    - simplefavorites
    - simplesaml
    - teamcomments
    - torque
    - exporttables
    - simplemaps
    - emulategroup
    - ECW2020
    # This should always go last, to run db updates and restart
    - finishmediawiki
