---

- name: Checkout SimpleFavorites
  git:
    repo: https://github.com/OpenTechStrategies/SimpleFavorites
    dest: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/extensions/SimpleFavorites/"
    version: 59fed33

- name: Enable SimpleFavorites
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/LocalSettings.php"
    line: "wfLoadExtension('SimpleFavorites');"
