---

- name: Check out SimpleFavorites
  git:
    repo: https://github.com/OpenTechStrategies/SimpleFavorites
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/extensions/SimpleFavorites/"
    version: cc069f1

- name: Enable SimpleFavorites
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    line: "wfLoadExtension('SimpleFavorites');"
