---

- name: Check out EmulateGroup
  git:
    repo: https://github.com/OpenTechStrategies/EmulateGroup
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/extensions/EmulateGroup/"
    version: 51dc009

- name: Transfer Config
  copy:
    src: emulategroup.php
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/"

- name: Enable EmulateGroup
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE EMULATEGROUP CONFIG"
    block: |
      include "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/emulategroup.php";
