---
- hosts: mysql
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mysql

- hosts: mediawiki
  become: true
  become_user: "{{ deployment_user }}"
  roles:
    - mediawiki
    - activitylog
    - simplebook
    - embed_video
    - permissions
    - picksome
    - simplefavorites
    - torque
    - teamcomments
    - exporttables
    - simplemaps
    - emulategroup
    - RPAColumbia
    # This should always go last, to run db updates and restart
    - finishmediawiki
