---

- name: Transfer LFC Logo
  copy:
    src: LeverForChange_Logo.png
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/resources/assets/LeverForChange_Logo.png"

- name: Install LFC Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    regexp: ^\$wgLogos = .*
    line: $wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/LeverForChange_Logo.png" ];

- name: Install TorqueDataConnect GlobalView Variables
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE PICKSOME OVERRIDE CONFIG"
    block: |
      $wgTorqueDataConnectMultiWikiConfig = [];
      $wgTorqueDataConnectMultiWikiConfig["LLIIA2020"] = "LLIIA2020";
      $wgTorqueDataConnectMultiWikiConfig["LFC100Change2020"] = "100Change2020";
      $wgTorqueDataConnectMultiWikiConfig["LFC100Change2017"] = "100Change2017";
      $wgTorqueDataConnectMultiWikiConfig["EO2020"] = "EO2020";
      $wgTorqueDataConnectMultiWikiConfig["RacialEquity2030"] = "RacialEquity2030";
      $wgTorqueDataConnectMultiWikiConfig["Climate2030"] = "Climate2030";
      $wgTorqueDataConnectMultiWikiConfig["ECW2020"] = "ECW2020";
      $wgTorqueDataConnectMultiWikiConfig["LoneStar2020"] = "LoneStar2020";
      $wgTorqueDataConnectMultiWikiConfig["Democracy22"] = "Democracy22";

- name: Install Team Comments Disabler
  copy:
    src: disableteamcomments.php
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/"

- name: Enable Team Comments Disabler
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE DISABLE TEAM COMMENTS"
    block: |
      include "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/disableteamcomments.php";

- name: Install SideBar View
  copy:
    src: sidebar_view.php
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/"

- name: Enable Team Comments Disabler
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE SIDEBAR VIEW"
    block: |
      include "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/torque-sites-config/sidebar_view.php";

# This is a nasty hack.  For certain large TOCs, mediawiki blows
# up with an error about the strip state being exceeded, as it's set to
# 5M.  These tocs are large enough to warrant a 10M size, however there's
# no way to pass this variable in.  So that means we need to actually chage
# the source code, which is a very brittle change and may break someday.
#
# It also might not.
- name: Change Strip State size limit
  tags: demo
  replace:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/includes/parser/StripState.php"
    regexp: "	protected \\$sizeLimit = 5000000;"
    replace: "	protected $sizeLimit = 10000000;"

