---

- name: Transfer LFC Logo
  copy:
    src: LeverForChange_Logo.png
    dest: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/resources/assets/LeverForChange_Logo.png"

- name: Install LFC Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/LocalSettings.php"
    regexp: ^\$wgLogo = .*
    line: $wgLogo = "$wgResourceBasePath/resources/assets/LeverForChange_Logo.png";

- name: Install TorqueDataConnect GlobalView Variables
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/LocalSettings.php"
    marker: "## {mark} ANSIBLE PICKSOME OVERRIDE CONFIG"
    block: |
      $wgTorqueDataConnectMultiWikiConfig = [];
      $wgTorqueDataConnectMultiWikiConfig["LLIIA2020"] = "LLIIA2020";
      $wgTorqueDataConnectMultiWikiConfig["LFC100Change2020"] = "100Change2020";
      $wgTorqueDataConnectMultiWikiConfig["LFC100Change2017"] = "100Change2017";
      $wgTorqueDataConnectMultiWikiConfig["EO2020"] = "EO2020";
      $wgTorqueDataConnectMultiWikiConfig["RacialEquity2030"] = "RacialEquity2030";
      $wgTorqueDataConnectMultiWikiConfig["Climate2030"] = "Climate2030";
      $wgTorqueDataConnectMultiWikiConfig["ECW2020"] = "ECW2020";
      $wgTorqueDataConnectMultiWikiConfig["LoneStar2020"] = "LoneStar2020";

- name: Install Team Comments Disabler
  copy:
    src: disableteamcomments.php
    dest: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/torque-sites-config/"

- name: Enable Team Comments Disabler
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-1.33.0/LocalSettings.php"
    marker: "## {mark} ANSIBLE DISABLE TEAM COMMENTS"
    block: |
      include "{{ mediawiki_install_directory }}/mediawiki-1.33.0/torque-sites-config/disableteamcomments.php";
