---

- name: Transfer LFC Logo
  copy:
    src: LeverForChange_Logo.svg
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/resources/assets/LeverForChange_Logo.svg"

- name: Install LFC Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    regexp: ^\$wgLogos = .*
    line: $wgLogos = [ 'svg' => "$wgResourceBasePath/resources/assets/LeverForChange_Logo.svg" ];

- name: Install Demo.php
  copy:
    src: "{{ item }}"
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/"
  loop:
    - demo.php
    - "{{ lookup('env','OTS_DIR') }}/clients/lever-for-change/torque-sites/100Change2020Demo/data/demo_header.php"
    - "{{ lookup('env','OTS_DIR') }}/clients/lever-for-change/torque-sites/100Change2020Demo/data/demo_footer.php"

- name: Install Demo Files
  unarchive:
    src: "{{ lookup('env','OTS_DIR') }}/clients/lever-for-change/torque-sites/100Change2020Demo/data/demo_files.tar.gz"
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/"
    creates: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/demo_files/"

- name: Enable Demo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    line: include "demo.php";
