---

- name: Add php repository - Ubuntu
  become_user: root
  apt_repository:
    repo: ppa:malteworld/ppa
  when: ansible_distribution == 'Ubuntu'

- name: install prerequisites
  become_user: root
  apt:
    name: "{{ item }}"
    update_cache: no
    state: present
  loop:
    - pdftk
    - python-pip
    - supervisor

- name: Setup installation directory
  file:
    path: "{{ mwlib_install_directory }}"
    state: directory

- name: Install virtualenv
  become_user: root
  pip:
    name: virtualenv

- name: Install mwlib via pip
  pip:
    virtualenv: "{{ mwlib_install_directory }}"
    name:
      - mwlib
      - mwlib.rl
      - pyfribidi
    chdir: "{{ mwlib_install_directory }}"

- name: Create Cache Directory
  file:
    path: "{{ mwlib_install_directory }}/cache/"
    state: directory

- name: Patch For TorqueData
  patch:
    src: MwlibTorqueData.patch
    strip: 1
    basedir: "{{ mwlib_install_directory }}"

- name: Install mwlib supervisor
  become_user: root
  template:
    src: supervisor-mwlib.conf.j2
    dest: /etc/supervisor/conf.d/mwlib.conf

- name: Restart supervisor for mwlib
  become_user: root
  supervisorctl:
    name: 'mwlib:'
    state: restarted
