---

# Because the permissions override MUST come after the original permissions, we
# delete it from the file, and then re-insert it to ensure that it comes at the
# end of the LocalSettings file
- name: Clear Permissions Override
  blockinfile:
    marker: "## {mark} ANSIBLE GROUP PERMISSIONS OVERRIDE CONFIG"
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"

- name: Add Permissions Override
  blockinfile:
    marker: "## {mark} ANSIBLE GROUP PERMISSIONS OVERRIDE CONFIG"
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    block: |
      $wgGroupPermissions['LFCResearchPartners']['teamcomment'] = false;

- name: Transfer Climate2030 Logo
  copy:
    src: Climate2030_Logo.png
    dest: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/resources/assets/Climate2030_Logo.png"

- name: Install Climate2030 Logo
  lineinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    regexp: ^\$wgLogos = .*
    line: $wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/Climate2030_Logo.png" ];

- name: Override base pluggable auth config
  blockinfile:
    path: "{{ mediawiki_install_directory }}/mediawiki-{{ mediawiki_version }}/LocalSettings.php"
    marker: "## {mark} ANSIBLE PLUGABLE AUTH OVERRIDE CONFIG"
    block: |
      $wgPluggableAuth_EnableLocalLogin = true;
